name: Release to Clojars

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.3
        with:
          bb: latest

      - name: Deploy to Clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: |
          mkdir -p ~/.m2
          echo "{:auth {:repository-auth {#\"clojars\" {:username \"${CLOJARS_USERNAME}\" :password \"${CLOJARS_PASSWORD}\"}}}}" > ~/.m2/settings.edn
          bb release