name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Node dependencies
      run: npm install

    - name: Install Babashka
      uses: just-sultanov/setup-babashka@v2
      with:
        version: '1.3.186'

    - name: Run tests
      run: bb test